version: '3.7'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /var/www/quiz
        volumes:
            - '.:/var/www/quiz'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=quiz
            - MYSQL_USER=quiz_username
            - MYSQL_PASSWORD=quiz_password
        ports:
            - '3307:3306'

    webserver:
        image: 'nginx:1.21.1'
        working_dir: /var/www/quiz
        volumes:
            - '.:/var/www/quiz'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        working_dir: /var/www/quiz
        volumes:
            - '.:/var/www/quiz'
